version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ecommerce_db
      DB_USER: root
      DB_PASS: example

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce_db
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-init:/docker-entrypoint-initdb.d  # Mount SQL scripts

volumes:
  db_data:
